network:
  max_connections: 10

data:
  cache_expiration: 300  # seconds (5 minutes)
  cache_max_size: 1000   # In-Scope max holders and their datas to be cached
  save_parallelism: 16  # number of active coroutines for saving data to the database
  sync_parallelism: 16

database:
  username: nikdekur
  password: e7yRu1XfZoIgbK0V